# default.conf — used for testing the config parser (Phase 3)

server {
    listen 127.0.0.1:8080;
    error_page 404 /errors/404.html;
    client_max_body_size 10M;

    location / {
        methods GET;
        root ./www;
        index index.html;
        autoindex off;
    }

    location /uploads {
        methods GET POST DELETE;
        root ./www;
        upload_store ./www/uploads;
        autoindex on;
    }

    location /cgi-bin {
        methods GET POST;
        root ./www;
        cgi_ext .py /usr/bin/python3;
    }

    location /old {
        return 301 /;
    }
}
