server {
    listen 127.0.0.1:8080;
    location / {
        methods GET;
        root ./www;
        index index.html;
    }
}

server {
    listen 127.0.0.1:8081;
    location / {
        methods GET;
        root ./www2;
        index index.html;
    }
}
